// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAITL_AVlbVn16sI5TX9BlAn-t0sVoNKQs',
    appId: '1:239930313729:web:ab982cf23152beb7474400',
    messagingSenderId: '239930313729',
    projectId: 'app-qlct-demo-02',
    authDomain: 'app-qlct-demo-02.firebaseapp.com',
    databaseURL: 'https://app-qlct-demo-02-default-rtdb.firebaseio.com',
    storageBucket: 'app-qlct-demo-02.firebasestorage.app',
    measurementId: 'G-EYKD3EZZP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRwK76YdfLyhGKq4ebo5Jzc1a1blEpnk',
    appId: '1:239930313729:android:133f51049e7be09d474400',
    messagingSenderId: '239930313729',
    projectId: 'app-qlct-demo-02',
    databaseURL: 'https://app-qlct-demo-02-default-rtdb.firebaseio.com',
    storageBucket: 'app-qlct-demo-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJztJAudH6O_sWMhe5i91R0IZ5XXGWZTw',
    appId: '1:239930313729:ios:a419d5b088e75abc474400',
    messagingSenderId: '239930313729',
    projectId: 'app-qlct-demo-02',
    databaseURL: 'https://app-qlct-demo-02-default-rtdb.firebaseio.com',
    storageBucket: 'app-qlct-demo-02.firebasestorage.app',
    iosClientId: '239930313729-vo65900esom8c72dqh2l9oolbbg5t0as.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlctDemo02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJztJAudH6O_sWMhe5i91R0IZ5XXGWZTw',
    appId: '1:239930313729:ios:a419d5b088e75abc474400',
    messagingSenderId: '239930313729',
    projectId: 'app-qlct-demo-02',
    databaseURL: 'https://app-qlct-demo-02-default-rtdb.firebaseio.com',
    storageBucket: 'app-qlct-demo-02.firebasestorage.app',
    iosClientId: '239930313729-vo65900esom8c72dqh2l9oolbbg5t0as.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQlctDemo02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAITL_AVlbVn16sI5TX9BlAn-t0sVoNKQs',
    appId: '1:239930313729:web:e3c96d338f1bc87f474400',
    messagingSenderId: '239930313729',
    projectId: 'app-qlct-demo-02',
    authDomain: 'app-qlct-demo-02.firebaseapp.com',
    databaseURL: 'https://app-qlct-demo-02-default-rtdb.firebaseio.com',
    storageBucket: 'app-qlct-demo-02.firebasestorage.app',
    measurementId: 'G-DVENDGDDHM',
  );

}